### ISSUE TITLE
Quickstart section in ReadMe incorrect for loading extension?

### ISSUE THREAD

**Issue by DeinAlptraum** [Jimmy-Blue/interactions-files#17]
The Readme claims you can load the extension via
`client.load('interactions-ext-files')`

This did not work for me ("Module not found" error).
Changing it to
`client.load("interactions.ext.files")`
worked without a problem

**Comment by B1ue-Dev** [comment]
Oh right. My bad. I will fix it later.
Thanks for letting me know that.

**Comment by B1ue-Dev** [comment]
Fixed with https://github.com/interactions-py/files/commit/6a0e33819cc1e08fa9f8f354e324514589d55495.
