### ISSUE TITLE
BytesIO support?

### ISSUE THREAD

**Issue by ghost** [Jimmy-Blue/interactions-files#7]
As with the StringIO sample, I am trying to send an image generated internally by BytesIO, but the image file of 0 bytes is sent.
Does this module support BytesIO?

**Comment by mAxYoLo01** [comment]
In fact yes it does support it, I have also done the same thing as you described (sending an image directly generated).
You can find my implementation over [here](https://github.com/BTE-France/BTE-France-Bot/blob/2ab33c9ff43e50025a73095e5550bbd74477d060/cogs/brush.py#L64).

**Comment by B1ue-Dev** [comment]
It does support.
Here is an example of how to use it:
```py
import aiohttp # We will read the image from an url.

url = "https://avatars.githubusercontent.com/u/98242689?s=200&v=4"
async with aiohttp.ClientSession() as session:
    async with session.get(url) as resp:
        if resp.status == 200:
            _io = (io.BytesIO(await resp.read())).read()
            file = interactions.File(file="unknown.png", fp=_io)
            await ctx.send(files=file)
```

**Comment by ghost** [comment]
I forgot to .seek(0) after using BytesIO
You can do it by using read.

We confirmed that it worked perfectly.
Thank you!
